name: build

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.10.0
        channel: stable
    - run: flutter doctor
    - run: flutter pub get
    - run: flutter test --coverage
    # - run: flutter build web
